[package]
name = "vm_virtual_blocks"
version = "0.1.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync-era"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]

[dependencies]
vise = { git = "https://github.com/matter-labs/vise.git", version = "0.1.0", rev = "9d097ab747b037b6e62504df1db5b975425b6bdd" }
zk_evm = { git = "https://github.com/matter-labs/era-zk_evm.git", tag = "v1.3.3-rc1" }
zksync_config = { path = "../../lib/config" }
zksync_types = { path = "../../lib/types" }
zksync_utils = { path = "../../lib/utils" }
zksync_state = { path = "../../lib/state" }
zksync_contracts = { path = "../../lib/contracts" }

anyhow = "1.0"
hex = "0.4"
itertools = "0.10"
once_cell = "1.7"
thiserror = "1.0"
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["time"] }
zksync_test_account = { path = "../../lib/test_account" }
ethabi = "18.0.0"
zksync_eth_signer = { path = "../../lib/eth_signer" }

