[package]
name = "zksync_eth_watch"
description = "ZKsync Ethereum watcher"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
vise.workspace = true
zksync_types.workspace = true
zksync_dal.workspace = true
zksync_contracts.workspace = true
zksync_system_constants.workspace = true
zksync_eth_client.workspace = true
zksync_shared_metrics.workspace = true

tokio = { workspace = true, features = ["time"] }
anyhow.workspace = true
thiserror.workspace = true
async-trait.workspace = true
tracing.workspace = true

[dev-dependencies]
zksync_concurrency.workspace = true
