[package]
name = "zksync_da_dispatcher"
description = "ZKsync data availability dispatcher"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true


[dependencies]
vise.workspace = true
zksync_dal = { workspace = true, features = ["node_framework"] }
zksync_config.workspace = true
zksync_types.workspace = true
zksync_da_client = { workspace = true, features = ["node_framework"] }
zksync_system_constants.workspace = true
zksync_node_framework.workspace = true
zksync_shared_di.workspace = true

tokio = { workspace = true, features = ["time"] }
anyhow.workspace = true
async-trait.workspace = true
tracing.workspace = true
chrono.workspace = true
rand.workspace = true
futures.workspace = true
