[package]
name = "vm_1_3_2"
version = "0.1.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync-era"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]

[dependencies]
zkevm-assembly = { git = "https://github.com/matter-labs/zkEVM-assembly.git", branch = "v1.3.2" }
zk_evm = { git = "https://github.com/matter-labs/zk_evm.git", branch = "v1.3.3" }

zksync_config = { path = "../../lib/config", version = "1.0" }
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_utils = { path = "../../lib/utils", version = "1.0" }
zksync_state = { path = "../../lib/state", version = "1.0" }

zksync_contracts = { path = "../../lib/contracts" }
vlog = { path = "../../lib/vlog", version = "1.0" }

anyhow = "1.0"
hex = "0.4"
itertools = "0.10"
metrics = "0.20"
ethabi = "18.0.0"
once_cell = "1.7"
thiserror = "1.0"

[dev-dependencies]
zksync_eth_signer = { path = "../../lib/eth_signer", version = "1.0" }
tokio = { version = "1", features = ["time"] }
