[package]
name = "zksync_prover"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync-2"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_dal = { path = "../../lib/dal", version = "1.0" }
zksync_config = { path = "../../lib/config", version = "1.0" }
zksync_utils = {path = "../../lib/utils", version = "1.0" }
zksync_prover_utils = {path = "../../lib/prover_utils", version = "1.0" }
zksync_circuit_breaker = {path = "../../lib/circuit_breaker", version = "1.0" }
prometheus_exporter = { path = "../../lib/prometheus_exporter", version = "1.0" }
vlog = { path = "../../lib/vlog", version = "1.0" }
zksync_verification_key_generator_and_server = { path = "../verification_key_generator_and_server", version = "1.0" }
zksync_object_store = { path = "../../lib/object_store", version = "1.0" }
setup_key_generator_and_server = { path = "../setup_key_generator_and_server", version = "1.0" }


api = { git = "https://github.com/matter-labs/heavy-ops-service.git", branch = "cleanup", features=["gpu"], default-features=false}
prover-service = { git = "https://github.com/matter-labs/heavy-ops-service.git", branch = "cleanup", features=["gpu"], default-features=false}

zkevm_test_harness = { git = "https://github.com/matter-labs/zkevm_test_harness.git", branch = "v1.3.1"}

tokio = { version = "1", features = ["time"] }
futures = { version = "0.3", features = ["compat"] }
ctrlc = { version = "3.1", features = ["termination"] }
thiserror = "1.0"
chrono = "0.4"
serde_json = "1.0"
ethabi = "16.0.0"
metrics = "0.20"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.2"
reqwest = { version = "0.11", features = ["blocking"] }
queues = "1.1.0"
local-ip-address = "0.5.0"
