[package]
name = "zksync_circuit_prover"
description = "ZKsync circuit prover binary implementation"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
tokio = { workspace = true, features = ["macros", "time"] }
tokio-util.workspace = true
anyhow.workspace = true
tracing.workspace = true
clap = { workspace = true, features = ["derive"] }
ctrlc = { workspace = true, features = ["termination"] }

zksync_prover_config.workspace = true
zksync_object_store.workspace = true
zksync_prover_dal.workspace = true
zksync_prover_fri_types.workspace = true
zksync_prover_keystore = { workspace = true, features = ["gpu-light"] }
zksync_task_management.workspace = true
zksync_circuit_prover_service.workspace = true
zksync_vlog.workspace = true

vise.workspace = true
shivini = { workspace = true, features = [
    "circuit_definitions",
    "zksync",
] }
