[package]
name = "zksync_circuit_prover"
description = "ZKsync circuit prover binary implementation"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
tokio = { workspace = true, features = ["macros", "time"] }
tokio-util.workspace = true
anyhow.workspace = true
async-trait.workspace = true
tracing.workspace = true
bincode.workspace = true
clap = { workspace = true, features = ["derive"] }

zksync_config = {workspace = true, features = ["observability_ext"]}
zksync_object_store.workspace = true
zksync_prover_dal.workspace = true
zksync_prover_fri_types.workspace = true
zksync_prover_fri_utils.workspace = true
zksync_queued_job_processor.workspace = true
zksync_types.workspace = true
zksync_prover_keystore = { workspace = true, features = ["gpu-light"] }
zksync_env_config.workspace = true
zksync_core_leftovers.workspace = true
zksync_utils.workspace = true
zksync_circuit_prover_service.workspace = true
zksync_prover_job_processor.workspace = true
zksync_vlog.workspace = true

vise.workspace = true
shivini = { workspace = true, features = [
    "circuit_definitions",
    "zksync",
] }
zkevm_test_harness.workspace = true
