[package]
name = "zksync_node_consensus"
description = "Consensus integration for ZKsync node"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zksync_config.workspace = true
zksync_concurrency.workspace = true
zksync_consensus_crypto.workspace = true
zksync_consensus_network.workspace = true
zksync_consensus_roles.workspace = true
zksync_consensus_storage.workspace = true
zksync_consensus_executor.workspace = true
zksync_consensus_bft.workspace = true
zksync_consensus_utils.workspace = true
zksync_contracts.workspace = true
zksync_protobuf.workspace = true
zksync_dal = { workspace = true, features = ["node_framework"] }
zksync_l1_contract_interface.workspace = true
zksync_metadata_calculator.workspace = true
zksync_merkle_tree.workspace = true
zksync_state_keeper.workspace = true
zksync_node_sync.workspace = true
zksync_system_constants.workspace = true
zksync_types.workspace = true
zksync_web3_decl= { workspace = true, features = ["node_framework"] }
zksync_state.workspace = true
zksync_vm_executor= { workspace = true, features = ["node_framework"] }
zksync_vm_interface.workspace = true
zksync_node_framework.workspace = true
zksync_shared_di.workspace = true

anyhow.workspace = true
async-trait.workspace = true
secrecy.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
semver.workspace = true
vise.workspace = true

[dev-dependencies]
zksync_node_genesis.workspace = true
zksync_node_test_utils.workspace = true
zksync_node_api_server.workspace = true
zksync_test_contracts.workspace = true

test-casing.workspace = true
rand.workspace = true
