[package]
name = "vm_m5"
version = "0.1.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync-2"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]

[dependencies]
zksync_crypto = { path = "../../lib/crypto" }
zksync_types = { path = "../../lib/types" }
zksync_utils = { path = "../../lib/utils" }
zksync_config = { path = "../../lib/config" }
zksync_state = { path = "../../lib/state" }
zksync_storage = { path = "../../lib/storage" }

zk_evm = { git = "https://github.com/matter-labs/era-zk_evm.git", tag = "v1.3.1-rc0" }
zksync_contracts = { path = "../../lib/contracts" }

hex = "0.4"
thiserror = "1.0"
itertools = "0.10"
once_cell = "1.7"
vlog = { path = "../../lib/vlog" }

tracing = "0.1"

[dev-dependencies]
tempfile = "3.0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
