[_metadata]
base = [
    'base/api.toml',
    'base/base_token_adjuster.toml',
    'base/chain.toml',
    'base/contract_verifier.toml',
    'base/contracts.toml',
    'base/database.toml',
    'base/eth_client.toml',
    'base/eth_sender.toml',
    'base/eth_watch.toml',
    'base/misc.toml',
    'base/object_store.toml',
    'base/nfs.toml',
    'base/rust.toml',
    'base/private.toml',
    'base/house_keeper.toml',
    'base/fri_prover.toml',
    'base/fri_witness_generator.toml',
    'base/fri_prover_group.toml',
    'base/proof_data_handler.toml',
    'base/fri_witness_vector_generator.toml',
    'base/fri_prover_gateway.toml',
    'base/fri_proof_compressor.toml',
]
