# Note: this file doesn't depend on `base` env and will not contain variables from there.
# All the variables must be provided explicitly.
# This is on purpose: if EN will accidentally depend on the main node env, it may cause problems.

test_database_url = "postgres://postgres@localhost:5433/zksync_local_test_ext_node"
database_url = "postgres://postgres@localhost/zksync_local_ext_node"
database_pool_size = 50
zksync_action="dont_ask"

[en]
http_port = 3060
ws_port = 3061
prometheus_port = 3322
healthcheck_port = 3081
threads_per_server = 128
l2_chain_id = 270
l1_chain_id = 9

req_entities_limit = 10000

state_cache_path = "./db/ext-node/state_keeper"
merkle_tree_path = "./db/ext-node/lightweight"
max_l1_batches_per_tree_iter = 20

main_node_url = "http://127.0.0.1:3050"
eth_client_url = "http://127.0.0.1:8545"

api_namespaces = ["eth", "web3", "net", "pubsub", "zks", "en", "debug"]

# Note:
# `bootloader_hash` and `default_aa_hash` are overridden from the `.init.env` values by `zk` tool.
bootloader_hash="0x0100038581be3d0e201b3cc45d151ef5cc59eb3a0f146ad44f0f72abf00b594c"
default_aa_hash="0x0100038dc66b69be75ec31653c64cb931678299b9b659472772b2550b703f41c"

[rust]
# `RUST_LOG` environment variable for `env_logger`
# Here we use TOML multiline strings: newlines will be trimmed.
log="""\
warn,\
zksync_core=debug,\
zksync_dal=info,\
zksync_eth_client=info,\
zksync_storage=info,\
zksync_merkle_tree=info,\
zksync_state=debug,\
zksync_utils=debug,\
zksync_types=info,\
loadnext=info,\
vm=info,\
zksync_external_node=info,\
cross_nodes_checker=debug,\
"""

# `RUST_BACKTRACE` variable
backtrace="full"
lib_backtrace="1"
