database_url = "postgres://postgres@postgres/zksync_local_ext_node"
template_database_url = "postgres://postgres@postgres/zksync_local"
test_database_url = "postgres://postgres@host:5433/zksync_local_test_ext_node"

[en]
l1_batch_commit_data_generator_mode = "Validium"
eth_client_url = "http://geth:8545"

[_metadata]
base = ["ext-node.toml"]
