version: '3.2'
services:
  postgres:
    image: "postgres:14"
    command: postgres -c 'max_connections=200'
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      interval: 1s
      timeout: 3s
      test: psql -U postgres -c "select exists (select * from pg_stat_activity where datname = '{{ database_name }}' and application_name = 'pg_restore')" | grep -e ".f$"
    environment:
      # We bind only to localhost, so setting insecure password is acceptable here
      - POSTGRES_PASSWORD=notsecurepassword
  external-node:
    image: "matterlabs/external-node:e03e201-1712331604214-linux-amd64"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - rocksdb:/usr/src/zksync/db
    expose:
      - 3060
      - 3061
      - 3081
    environment:
      DATABASE_URL: "postgres://postgres:notsecurepassword@postgres/zksync_local_ext_node"
      DATABASE_POOL_SIZE: 10

      EN_HTTP_PORT: 3060
      EN_WS_PORT: 3061
      EN_HEALTHCHECK_PORT: 3081
      EN_ETH_CLIENT_URL: https://ethereum-rpc.publicnode.com
      EN_MAIN_NODE_URL: https://zksync2-mainnet.zksync.io
      EN_L1_CHAIN_ID: 1
      EN_L2_CHAIN_ID: 324

      EN_STATE_CACHE_PATH: "./db/ext-node/state_keeper"
      EN_MERKLE_TREE_PATH: "./db/ext-node/lightweight"
      EN_SNAPSHOTS_OBJECT_STORE_BUCKET_BASE_URL: "zksync-era-mainnet-external-node-snapshots"
      EN_SNAPSHOTS_OBJECT_STORE_MODE: "GCSAnonymousReadOnly"
      RUST_LOG: "zksync_core=debug,zksync_dal=info,zksync_eth_client=info,zksync_merkle_tree=info,zksync_storage=info,zksync_state=debug,zksync_types=info,vm=info,zksync_external_node=info,zksync_utils=debug,zksync_snapshots_applier=info"
    command:
      - --enable-snapshots-recovery

volumes:
  postgres:
  rocksdb:
