[package]
name = "zk_inception"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
authors.workspace = true
exclude.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
cliclack.workspace = true
config.workspace = true
console.workspace = true
human-panic.workspace = true
lazy_static.workspace = true
serde_yaml.workspace = true
serde.workspace = true
serde_json.workspace = true
xshell.workspace = true
ethers.workspace = true
common.workspace = true
tokio.workspace = true
types.workspace = true
strum.workspace = true
toml.workspace = true
url.workspace = true
thiserror.workspace = true
zksync_config.workspace = true
slugify-rs.workspace = true
zksync_basic_types.workspace = true
clap-markdown.workspace = true
zksync_consensus_roles.workspace = true
zksync_consensus_crypto.workspace = true
secrecy.workspace = true
