[package]
name = "zksync_os_sequencer"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]

zk_os_forward_system.workspace = true
zk_ee.workspace = true
zk_os_basic_system.workspace = true
zksync_storage.workspace = true
zksync_zkos_vm_runner.workspace = true

anyhow.workspace = true
ruint.workspace = true
tokio = { workspace = true, features = ["full"] }

tracing.workspace = true
tracing-subscriber.workspace = true
hex.workspace = true
async-trait.workspace = true
thiserror.workspace = true
itertools.workspace = true
futures.workspace = true
dashmap.workspace = true
vise.workspace = true
zksync_vlog.workspace = true
zksync_zk_os_merkle_tree.workspace = true

serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_with = "3.13.0"
serde_yaml = "0.9.33"

zksync_web3_decl = { workspace = true, features = ["server"] }
zksync_types.workspace = true
crossbeam-queue = "0.3.12"
futures-core = "0.3.31"
time = "0.3.37"
futures-util = "0.3.31"
alloy = "1.0.12"
bincode = "1.3.3"
