[package]
name = "zksync_contract_verification_server"
description = "ZKsync contract verification server"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zksync_config.workspace = true
zksync_dal.workspace = true
zksync_types.workspace = true
vise.workspace = true

anyhow.workspace = true
axum.workspace = true
tokio = { workspace = true, features = ["time"] }
tower-http = { workspace = true, features = ["cors"] }
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
