[package]
name = "zksync_node_framework"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
prometheus_exporter.workspace = true
zksync_types.workspace = true
zksync_health_check.workspace = true
zksync_dal.workspace = true
prover_dal.workspace = true
zksync_db_connection.workspace = true
zksync_config.workspace = true
zksync_state.workspace = true
zksync_object_store.workspace = true
zksync_core.workspace = true
zksync_storage.workspace = true
zksync_eth_client.workspace = true
zksync_contracts.workspace = true
zksync_web3_decl.workspace = true
zksync_utils.workspace = true

tracing.workspace = true
thiserror.workspace = true
async-trait.workspace = true
futures.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["rt"] }
ctrlc.workspace = true

[dev-dependencies]
zksync_env_config.workspace = true
vlog.workspace = true
assert_matches.workspace = true
