[package]
name = "zksync_node_framework"
version = "0.1.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync-era"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]

[dependencies]
prometheus_exporter = { path = "../../lib/prometheus_exporter" }
zksync_types = { path = "../../lib/types" }
zksync_health_check = { path = "../../lib/health_check" }
zksync_dal = { path = "../../lib/dal" }
zksync_config = { path = "../../lib/config" }
zksync_object_store = { path = "../../lib/object_store" }
zksync_core = { path = "../../lib/zksync_core" }
zksync_storage = { path = "../../lib/storage" }
zksync_eth_client = { path = "../../lib/eth_client" }

tracing = "0.1"
thiserror = "1"
async-trait = "0.1"
futures = "0.3"
anyhow = "1"
tokio = { version = "1", features = ["rt"] }

[dev-dependencies]
zksync_env_config = { path = "../../lib/env_config" }
vlog = { path = "../../lib/vlog" }
assert_matches = "1.5.0"
