[package]
name = "zksync_tee_proof_data_handler"
description = "ZKsync TEE proof data handler API"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
chrono.workspace = true
vise.workspace = true
zksync_config.workspace = true
zksync_dal.workspace = true
zksync_object_store.workspace = true
zksync_prover_interface.workspace = true
zksync_tee_prover_interface.workspace = true
zksync_types.workspace = true
zksync_vm_executor.workspace = true
anyhow.workspace = true
axum.workspace = true
tokio.workspace = true
tower-http = { workspace = true, features = ["compression-zstd", "decompression-zstd"] }
tracing.workspace = true
reqwest.workspace = true
tower.workspace = true
jsonrpsee = { workspace = true, features = ["async-client", "ws-client", "macros", "client-ws-transport-tls"] }
thiserror.workspace = true

[dev-dependencies]
hyper.workspace = true
zksync_multivm.workspace = true
serde_json.workspace = true
tower = { workspace = true, features = ["util"] }
zksync_contracts.workspace = true
