[package]
name = "zksync_tee_proof_data_handler"
description = "ZKsync TEE proof data handler API"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
hex.workspace = true
intel-dcap-api = "0.6.0"
jsonrpsee = { workspace = true, features = [
  "async-client",
  "ws-client",
  "macros",
  "client-ws-transport-tls",
] }
reqwest.workspace = true
secp256k1 = { workspace = true, features = [
  "global-context",
  "recovery",
  "serde",
] }
serde_json.workspace = true
sha2.workspace = true
teepot = { version = "0.6.0", default-features = false }
thiserror.workspace = true
tokio.workspace = true
tower-http = { workspace = true, features = [
  "compression-zstd",
  "decompression-zstd",
] }
tower.workspace = true
tracing.workspace = true
vise.workspace = true
x509-cert = { workspace = true, features = ["builder", "signature", "default"] }
zksync_config.workspace = true
zksync_dal = { workspace = true, features = ["node_framework"] }
zksync_node_framework.workspace = true
zksync_object_store = { workspace = true, features = ["node_framework"] }
zksync_prover_interface.workspace = true
zksync_tee_prover_interface.workspace = true
zksync_types.workspace = true
zksync_vm_executor.workspace = true
zksync_contracts.workspace = true
zksync_l1_contract_interface.workspace = true
zksync_crypto_primitives.workspace = true

[dev-dependencies]
hyper.workspace = true
zksync_multivm.workspace = true
serde_json.workspace = true
tower = { workspace = true, features = ["util"] }
zksync_contracts.workspace = true
