[package]
name = "zksync_external_proof_integration_api"
description = "ZKsync external proof integration API"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
axum = { workspace = true, features = ["multipart"] }
async-trait.workspace = true
tracing.workspace = true
thiserror.workspace = true
zksync_prover_interface.workspace = true
zksync_basic_types.workspace = true
zksync_object_store.workspace = true
zksync_proof_data_handler.workspace = true
zksync_dal.workspace = true
tokio.workspace = true
bincode.workspace = true
anyhow.workspace = true
vise.workspace = true
