postgres:
  max_connections: 100
  statement_timeout_sec: 300
  test:
    server_url: postgres://postgres:notsecurepassword@localhost:5433/zksync_local_test
    prover_url: postgres://postgres:notsecurepassword@localhost:5433/prover_local_test
api:
  web3_json_rpc:
    http_port: 3150
    http_url: http://127.0.0.1:3150/
    ws_port: 3151
    ws_url: ws://127.0.0.1:3151/
    req_entities_limit: 10000
    filters_limit: 10000
    subscriptions_limit: 10000
    pubsub_polling_interval: 200
    max_nonce_ahead: 20
    gas_price_scale_factor: 1.5
    estimate_gas_scale_factor: 1.3
    estimate_gas_acceptable_overestimation: 5000
    max_tx_size: 1000000
    filters_disabled: false
    api_namespaces:
    - en
    - eth
    - net
    - web3
    - zks
    - pubsub
    - debug
    extended_api_tracing: false
  prometheus:
    listener_port: 3412
    pushgateway_url: http://127.0.0.1:9091
    push_interval_ms: 100
  healthcheck:
    port: 3171
  merkle_tree:
    port: 3172
contract_verifier:
  port: 3170
  url: http://127.0.0.1:3170/
  compilation_timeout: 240
  polling_interval: 1000
  threads_per_server: 128
  prometheus_port: 3314
circuit_breaker:
  sync_interval_ms: 120000
  http_req_max_retry_number: 10
  http_req_retry_interval_sec: 2
  replication_lag_limit_sec: 100
mempool:
  sync_interval_ms: 10
  sync_batch_size: 1000
  capacity: 10000000
  stuck_tx_timeout: 172800
  remove_stuck_txs: true
  delay_interval: 100
operations_manager:
  delay_interval: 100
state_keeper:
  transaction_slots: 8192
  block_commit_deadline_ms: 2500
  miniblock_commit_deadline_ms: 1000
  miniblock_seal_queue_capacity: 10
  max_single_tx_gas: 15000000
  max_allowed_l2_tx_gas_limit: 15000000000
  reject_tx_at_geometry_percentage: 0.95
  reject_tx_at_eth_params_percentage: 0.95
  reject_tx_at_gas_percentage: 0.95
  close_block_at_geometry_percentage: 0.95
  close_block_at_eth_params_percentage: 0.95
  close_block_at_gas_percentage: 0.95
  minimal_l2_gas_price: 100000000
  compute_overhead_part: 0.0
  pubdata_overhead_part: 1.0
  batch_overhead_l1_gas: 800000
  max_gas_per_batch: 200000000
  max_pubdata_per_batch: 500000
  fee_model_version: V2
  validation_computational_gas_limit: 300000
  save_call_traces: true
  max_circuits_per_batch: 31100
  miniblock_max_payload_size: 1000000
  protective_reads_persistence_enabled: false
house_keeper:
  l1_batch_metrics_reporting_interval_ms: 10000
prover:
  setup_data_path: data/keys
  prometheus_port: 3315
  max_attempts: 10
  generation_timeout_in_secs: 600
  setup_load_mode: FROM_DISK
  specialized_group_id: 100
  queue_capacity: 10
  witness_vector_receiver_port: 3316
  zone_read_url: http://metadata.google.internal/computeMetadata/v1/instance/zone
  shall_save_to_public_bucket: true
  availability_check_interval_in_secs: 10000
  public_object_store:
    file_backed:
      file_backed_base_path: artifacts
    max_retries: 10
  prover_object_store:
    file_backed:
      file_backed_base_path: artifacts
    max_retries: 10
  cloud_type: LOCAL
prometheus:
  listener_port: 3412
  pushgateway_url: http://127.0.0.1:9091
  push_interval_ms: 100
db:
  state_keeper_db_path: ./db/main/state_keeper
  merkle_tree:
    path: ./db/main/tree
    mode: FULL
    multi_get_chunk_size: 500
    block_cache_size_mb: 128
    memtable_capacity_mb: 256
    stalled_writes_timeout_sec: 60
    max_l1_batches_per_iter: 20
  experimental:
    state_keeper_db_block_cache_capacity_mb: 128
    reads_persistence_enabled: false
    processing_delay_ms: 0
    include_indices_and_filters_in_block_cache: false
eth:
  sender:
    aggregated_proof_sizes:
    - 1
    wait_confirmations: 1
    tx_poll_period: 1
    aggregate_tx_poll_period: 1
    max_txs_in_flight: 30
    proof_sending_mode: SKIP_EVERY_PROOF
    max_aggregated_tx_gas: 15000000
    max_eth_tx_data_size: 120000
    max_aggregated_blocks_to_commit: 1
    max_aggregated_blocks_to_execute: 45
    aggregated_block_commit_deadline: 1
    aggregated_block_prove_deadline: 10
    aggregated_block_execute_deadline: 10
    timestamp_criteria_max_allowed_lag: 30
    max_acceptable_priority_fee_in_gwei: 100000000000
    pubdata_sending_mode: BLOBS
    tx_aggregation_paused: false
    tx_aggregation_only_prove_and_execute: false
  gas_adjuster:
    default_priority_fee_per_gas: 1000000000
    max_base_fee_samples: 100
    pricing_formula_parameter_a: 1.5
    pricing_formula_parameter_b: 1.001
    internal_l1_pricing_multiplier: 0.8
    poll_period: 5
    num_samples_for_blob_base_fee_estimate: 10
    internal_pubdata_pricing_multiplier: 1.0
  watcher:
    confirmations_for_eth_event: 0
    eth_node_poll_interval: 300
witness_generator:
  generation_timeout_in_secs: 900
  max_attempts: 10
  shall_save_to_public_bucket: true
  prometheus_listener_port: 3116
  max_circuits_in_flight: 500
witness_vector_generator:
  max_prover_reservation_duration_in_secs: 1000
  prover_instance_wait_timeout_in_secs: 200
  prover_instance_poll_time_in_milli_secs: 250
  prometheus_listener_port: 3420
  prometheus_pushgateway_url: http://127.0.0.1:9091
  prometheus_push_interval_ms: 100
  specialized_group_id: 100
proof_compressor:
  compression_mode: 1
  prometheus_listener_port: 3321
  prometheus_pushgateway_url: http://127.0.0.1:9091
  prometheus_push_interval_ms: 100
  generation_timeout_in_secs: 3600
  max_attempts: 5
  universal_setup_path: keys/setup/setup_2^24.key
  universal_setup_download_url: https://storage.googleapis.com/matterlabs-setup-keys-us/setup-keys/setup_2^24.key
  verify_wrapper_proof: true
data_handler:
  http_port: 3320
  proof_generation_timeout_in_secs: 18000
  tee_support: true
prover_group:
  group_0:
  - circuit_id: 1
    aggregation_round: 4
  - circuit_id: 2
    aggregation_round: 2
  - circuit_id: 255
    aggregation_round: 0
  group_1:
  - circuit_id: 1
    aggregation_round: 0
  group_2:
  - circuit_id: 2
    aggregation_round: 0
  - circuit_id: 4
    aggregation_round: 0
  - circuit_id: 6
    aggregation_round: 0
  - circuit_id: 9
    aggregation_round: 0
  group_3:
  - circuit_id: 3
    aggregation_round: 0
  group_4:
  - circuit_id: 11
    aggregation_round: 0
  - circuit_id: 12
    aggregation_round: 0
  - circuit_id: 13
    aggregation_round: 0
  group_5:
  - circuit_id: 5
    aggregation_round: 0
  group_6:
  - circuit_id: 3
    aggregation_round: 1
  group_7:
  - circuit_id: 7
    aggregation_round: 0
  group_8:
  - circuit_id: 8
    aggregation_round: 0
  group_9:
  - circuit_id: 12
    aggregation_round: 1
  - circuit_id: 13
    aggregation_round: 1
  - circuit_id: 14
    aggregation_round: 1
  - circuit_id: 15
    aggregation_round: 1
  group_10:
  - circuit_id: 10
    aggregation_round: 0
  group_11:
  - circuit_id: 7
    aggregation_round: 1
  - circuit_id: 8
    aggregation_round: 1
  - circuit_id: 10
    aggregation_round: 1
  - circuit_id: 11
    aggregation_round: 1
  group_12:
  - circuit_id: 4
    aggregation_round: 1
  - circuit_id: 5
    aggregation_round: 1
  - circuit_id: 6
    aggregation_round: 1
  - circuit_id: 9
    aggregation_round: 1
  group_13:
  - circuit_id: 14
    aggregation_round: 0
  - circuit_id: 15
    aggregation_round: 0
  - circuit_id: 255
    aggregation_round: 0
  group_14:
  - circuit_id: 16
    aggregation_round: 1
  - circuit_id: 17
    aggregation_round: 1
  - circuit_id: 18
    aggregation_round: 1
prover_gateway:
  api_url: http://127.0.0.1:3320
  api_poll_duration_secs: 1000
  prometheus_listener_port: 3310
  prometheus_pushgateway_url: http://127.0.0.1:9091
  prometheus_push_interval_ms: 100
snapshot_creator:
  storage_logs_chunk_size: 1000000
  concurrent_queries_count: 25
  object_store:
    file_backed:
      file_backed_base_path: artifacts
    max_retries: 10
  version: 0
observability:
  log_format: plain
  log_directives: zksync_node_test_utils=info,zksync_state_keeper=info,zksync_reorg_detector=info,zksync_consistency_checker=info,zksync_metadata_calculator=info,zksync_node_sync=info,zksync_node_consensus=info,zksync_contract_verification_server=info,zksync_node_api_server=info,zksync_tee_verifier_input_producer=info,zksync_node_framework=info,zksync_block_reverter=info,zksync_commitment_generator=info,zksync_node_db_pruner=info,zksync_eth_sender=info,zksync_node_fee_model=info,zksync_node_genesis=info,zksync_house_keeper=info,zksync_proof_data_handler=info,zksync_shared_metrics=info,zksync_node_test_utils=info,zksync_vm_runner=info,zksync_consensus_bft=info,zksync_consensus_network=info,zksync_consensus_storage=info,zksync_core_leftovers=debug,zksync_server=debug,zksync_contract_verifier=debug,zksync_dal=info,zksync_db_connection=info,zksync_eth_client=info,zksync_eth_watch=debug,zksync_storage=info,zksync_db_manager=info,zksync_merkle_tree=info,zksync_state=debug,zksync_utils=debug,zksync_queued_job_processor=info,zksync_types=info,zksync_mempool=debug,loadnext=info,vm=info,zksync_object_store=info,zksync_external_node=info,zksync_witness_generator=info,zksync_prover_fri=info,zksync_witness_vector_generator=info,zksync_web3_decl=debug,zksync_health_check=debug,zksync_proof_fri_compressor=info,vise_exporter=error,snapshots_creator=debug,zksync_base_token_adjuster=debug,zksync_external_price_api=debug,zksync_external_proof_integration_api=info
protective_reads_writer:
  db_path: ./db/main/protective_reads
  window_size: 3
  first_processed_batch: 0
core_object_store:
  file_backed:
    file_backed_base_path: artifacts
  max_retries: 10
snapshot_recovery:
  enabled: false
  postgres:
    max_concurrency: 10
  tree:
    chunk_size: 200000
  object_store:
    file_backed:
      file_backed_base_path: artifacts
    max_retries: 100
  experimental:
    tree_recovery_parallel_persistence_buffer: 1
    drop_storage_key_preimages: true
pruning:
  enabled: true
  chunk_size: 10
  removal_delay_sec: 60
  data_retention_sec: 3600
commitment_generator:
  max_parallelism: 10
da_dispatcher:
  polling_interval_ms: 5000
  max_rows_to_dispatch: 100
  max_retries: 5
base_token_adjuster:
  price_polling_interval_ms: 30000
  price_cache_update_interval_ms: 2000
  max_tx_gas: 80000
  default_priority_fee_per_gas: 1000000
  max_acceptable_priority_fee_in_gwei: 100000000000
  l1_receipt_checking_sleep_ms: 30000
  l1_receipt_checking_max_attempts: 3
  l1_tx_sending_max_attempts: 3
  l1_tx_sending_sleep_ms: 30000
  halt_on_error: false
  price_fetching_max_attempts: 3
  price_fetching_sleep_ms: 5000
  l1_update_deviation_percentage: 10
basic_witness_input_producer:
  db_path: ./db/main/basic_witness_input_producer
  window_size: 3
  first_processed_batch: 0
external_price_api_client:
  source: forced
  client_timeout_ms: 10000
  forced_numerator: 3
  forced_denominator: 2
external_proof_integration_api:
  http_port: 3073
experimental_vm:
  playground:
    fast_vm_mode: SHADOW
    db_path: ./db/main/vm_playground
    first_processed_batch: 0
    reset: false
    window_size: 1
  state_keeper_fast_vm_mode: OLD
prover_job_monitor:
  prometheus_port: 3317
  max_db_connections: 9
  graceful_shutdown_timeout_ms: 5000
  gpu_prover_archiver_run_interval_ms: 86400000
  gpu_prover_archiver_archive_prover_after_ms: 172800000
  prover_jobs_archiver_run_interval_ms: 1800000
  prover_jobs_archiver_archive_jobs_after_ms: 172800000
  proof_compressor_job_requeuer_run_interval_ms: 10000
  prover_job_requeuer_run_interval_ms: 10000
  witness_generator_job_requeuer_run_interval_ms: 10000
  proof_compressor_queue_reporter_run_interval_ms: 10000
  prover_queue_reporter_run_interval_ms: 10000
  witness_generator_queue_reporter_run_interval_ms: 10000
  witness_job_queuer_run_interval_ms: 10000
