sqlx_offline = true
database_url = "postgres://postgres:notsecurepassword@postgres/zksync_local"
database_prover_url = "postgres://postgres:notsecurepassword@postgres/prover_local"
test_database_url = "postgres://postgres:notsecurepassword@host:5433/zksync_local_test"
test_database_prover_url = "postgres://postgres:notsecurepassword@host:5433/prover_local_test"

# for loadtest
l1_rpc_address = "http://reth:8545"

[eth_client]
web3_url = "http://reth:8545"

[chain.state_keeper]
miniblock_iteration_interval = 50

[_metadata]
base = ["dev.toml"]
