database_url = "postgres://postgres:notsecurepassword@postgres/_ext_node"
template_database_url = "postgres://postgres:notsecurepassword@postgres/zksync_local"
test_database_url = "postgres://postgres:notsecurepassword@host:5433/zksync_local_test_ext_node"

[en]
eth_client_url = "http://geth:8545"

[_metadata]
base = ["ext-node.toml"]
