__imports__ = ["base", "l1-inits/.init.env", "l2-inits/dev2.init.env" ]
ZKSYNC_DEBUG_LOGS=true

CONTRACTS_SHARED_BRIDGE_UPGRADE_STORAGE_SWITCH="0"
CHAIN_ETH_ZKSYNC_NETWORK_ID=273
ZKSYNC_ACTION="dont_ask"
CONTRACTS_ERA_CHAIN_ID="270"

ETH_SENDER_SENDER_OPERATOR_PRIVATE_KEY="0xf12e28c0eb1ef4ff90478f6805b68d63737b7f33abfa091601140805da450d93"
ETH_SENDER_SENDER_OPERATOR_COMMIT_ETH_ADDR="0x8002cD98Cfb563492A6fB3E7C8243b7B9Ad4cc92"
ETH_SENDER_SENDER_OPERATOR_BLOBS_PRIVATE_KEY="0x850683b40d4a740aa6e745f889a6fdc8327be76e122f5aba645a5b02d0248db8"
ETH_SENDER_SENDER_OPERATOR_BLOBS_ETH_ADDR="0xA13c10C0D5bd6f79041B9835c63f91de35A15883"
ETH_SENDER_SENDER_OPERATOR_GATEWAY_PRIVATE_KEY="0xf12e28c0eb1ef4ff90478f6805b68d63737b7f33abfa091601140805da450d93"
