[package]
name = "verified_sources_fetcher"
description = "Tool to fetch verified contract sources"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
zksync_dal.workspace = true
zksync_types = { workspace = true, features = ["contract-verification"] }
zksync_config.workspace = true

anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
serde_json.workspace = true
