[package]
name = "zksync_contract_verifier"
description = "The zkEVM contract verifier"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
zksync_dal.workspace = true
zksync_env_config.workspace = true
zksync_config.workspace = true
zksync_contract_verifier_lib.workspace = true
zksync_queued_job_processor.workspace = true
zksync_utils.workspace = true
zksync_vlog.workspace = true

anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
futures.workspace = true
ctrlc.workspace = true
structopt.workspace = true
tracing.workspace = true
