[package]
name = "zksync_zkos_prover_input_generator"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zksync_dal.workspace = true
zksync_state.workspace = true
zksync_storage.workspace = true
zksync_state_keeper.workspace = true
zksync_utils.workspace = true
zksync_mempool.workspace = true
zksync_types.workspace = true
zksync_zkos_vm_runner.workspace = true
zksync_vm_interface.workspace = true
zksync_config.workspace = true
zksync_node_fee_model.workspace = true
zksync_protobuf.workspace = true
# todo: maybe this dependency should be avoided
zksync_l1_contract_interface.workspace = true
proof_cache.workspace = true

zk_os_forward_system.workspace = true
zk_ee.workspace = true
zk_os_basic_system.workspace = true
air-compiler-cli.workspace = true
execution_utils.workspace = true
verifier_common.workspace = true
full_statement_verifier = { workspace = true, optional = true }

anyhow.workspace = true
ruint.workspace = true
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
hex.workspace = true
async-trait.workspace = true
thiserror.workspace = true
itertools.workspace = true
futures.workspace = true
http.workspace = true
tracing-subscriber.workspace = true
base64.workspace = true
vise.workspace = true

axum.workspace = true
bincode.workspace = true

[features]

include_verifiers = ["full_statement_verifier"]