# Configuration for the Base Token Adjuster crate

[base_token_adjuster]

# How often to poll external price feeds for the base token price.
price_polling_interval_ms = "30000"

price_cache_update_interval_ms = "2000"

max_tx_gas = "80000"

default_priority_fee_per_gas = "1000000"
