# Addresses of the deployed ZKsync contracts.
# Values of this file are updated automatically by the contract deploy script.

[contracts]
ADMIN_FACET_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
DIAMOND_INIT_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
DIAMOND_UPGRADE_INIT_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
DEFAULT_UPGRADE_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
MAILBOX_FACET_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
EXECUTOR_FACET_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
GOVERNANCE_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
GETTERS_FACET_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
VERIFIER_ADDR = "0xDAbb67b676F5b01FcC8997Cc8439846D0d8078ca"
DIAMOND_PROXY_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_MULTICALL3_ADDR = "0xcA11bde05977b3631167028862bE2a173976CA11"
L1_ERC20_BRIDGE_PROXY_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_ERC20_BRIDGE_IMPL_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L2_TESTNET_PAYMASTER_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_ALLOW_LIST_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
CREATE2_FACTORY_ADDR = "0xce0042B868300000d44A59004Da54A005ffdcf9f"
VALIDATOR_TIMELOCK_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
VALIDATOR_TIMELOCK_EXECUTION_DELAY = 0
RECURSION_SCHEDULER_LEVEL_VK_HASH = "0x18518ce15be02847459f304b1567cb914ae357eca82af07c09582e78592b987b"
RECURSION_NODE_LEVEL_VK_HASH = "0x1186ec268d49f1905f8d9c1e9d39fc33e98c74f91d91a21b8f7ef78bd09a8db8"
RECURSION_LEAF_LEVEL_VK_HASH = "0x101e08b00193e529145ee09823378ef51a3bc8966504064f1f6ba3f1ba863210"
RECURSION_CIRCUITS_SET_VKS_HASH = "0x18c1639094f58177409186e8c48d9f577c9410901d2f1d486b3e7d6cf553ae4c"
GENESIS_TX_HASH = "0xb99ebfea46cbe05a21cd80fe5597d97b204befc52a16303f579c607dc1ac2e2e"
PRIORITY_TX_MAX_GAS_LIMIT = 72000000
DEPLOY_L2_BRIDGE_COUNTERPART_GAS_LIMIT = 10000000
GENESIS_PROTOCOL_VERSION = "26"
GENESIS_PROTOCOL_SEMANTIC_VERSION = "0.26.0"
L1_WETH_BRIDGE_IMPL_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L1_WETH_BRIDGE_PROXY_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L1_WETH_TOKEN_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L2_WETH_BRIDGE_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L2_WETH_TOKEN_IMPL_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L2_WETH_TOKEN_PROXY_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"

GENESIS_ROOT = "0x09e68951458b18c24ae5f4100160b53c4888c9b3c3c1859cc674bc02236675ad"
GENESIS_BATCH_COMMITMENT = "0x7238eab6a0e9f5bb84421feae6b6b9ae80816d490c875d29ff3ded375a3e078f"
GENESIS_ROLLUP_LEAF_INDEX = "64"

# Ecosystem-wide params
L1_ROLLUP_DA_VALIDATOR = "0x0000000000000000000000000000000000000000"
L1_VALIDIUM_DA_VALIDATOR = "0x0000000000000000000000000000000000000000"

# Chain-specific params
L1_DA_VALIDATOR_ADDR = "0x0000000000000000000000000000000000000000"
L2_DA_VALIDATOR_ADDR = "0x0000000000000000000000000000000000000000"
L1_RELAYED_SL_DA_VALIDATOR = "0x0000000000000000000000000000000000000000"

L1_SHARED_BRIDGE_IMPL_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
# These are currently not used, but will be used once the shared bridge is up
BRIDGEHUB_PROXY_ADDR = "0x0000000000000000000000000000000000000000"
BRIDGEHUB_IMPL_ADDR = "0x0000000000000000000000000000000000000000"
STATE_TRANSITION_PROXY_ADDR = "0x0000000000000000000000000000000000000000"
STATE_TRANSITION_IMPL_ADDR = "0x0000000000000000000000000000000000000000"
TRANSPARENT_PROXY_ADMIN_ADDR = "0x0000000000000000000000000000000000000000"
L2_PROXY_ADMIN_ADDR = "0x0000000000000000000000000000000000000000"
BASE_TOKEN_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
BASE_TOKEN_BRIDGE_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
GENESIS_UPGRADE_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
MAX_NUMBER_OF_ZK_CHAINS = 100
L1_SHARED_BRIDGE_PROXY_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_NATIVE_TOKEN_VAULT_IMPL_ADDR ="0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_NATIVE_TOKEN_VAULT_PROXY_ADDR ="0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L2_NATIVE_TOKEN_VAULT_IMPL_ADDR = "0x0000000000000000000000000000000000010004"
L2_NATIVE_TOKEN_VAULT_PROXY_ADDR = "0x0000000000000000000000000000000000010004"
L2_SHARED_BRIDGE_IMPL_ADDR = "0x0000000000000000000000000000000000010003"
L2_SHARED_BRIDGE_ADDR =      "0x0000000000000000000000000000000000010003"
L2_ERC20_BRIDGE_ADDR =       "0x0000000000000000000000000000000000010003"
CTM_DEPLOYMENT_TRACKER_IMPL_ADDR ="0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
CTM_DEPLOYMENT_TRACKER_PROXY_ADDR ="0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
MESSAGE_ROOT_IMPL_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
MESSAGE_ROOT_PROXY_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_NULLIFIER_IMPL_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_NULLIFIER_PROXY_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_BRIDGED_STANDARD_ERC20_IMPL_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_BRIDGED_TOKEN_BEACON_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L2_LEGACY_SHARED_BRIDGE_IMPL_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L2_LEGACY_SHARED_BRIDGE_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
FRI_RECURSION_LEAF_LEVEL_VK_HASH ="0x5a11d22ec76c8af17e5945e8f82f97b2e076a5654eb5807ed210a54fce7093f0"
FRI_RECURSION_NODE_LEVEL_VK_HASH ="0xf520cd5b37e74e19fdb369c8d676a04dce8a19457497ac6686d2bb95d94109c8"
FRI_RECURSION_SCHEDULER_LEVEL_VK_HASH ="0x7e4ad3251ad738ed8a6acdf7a34d9dfe378ad516efcb098448cf14d5f2c0c90e"
SNARK_WRAPPER_VK_HASH ="0x14f97b81e54b35fe673d8708cc1a19e1ea5b5e348e12d31e39824ed4f42bbca2"
FFLONK_SNARK_WRAPPER_VK_HASH = "0x560b19cfd6bcf1049c6409c18d81db288ab7639db080ed3b48df17ddfbcc4666"
SHARED_BRIDGE_UPGRADE_STORAGE_SWITCH = 0
ERA_CHAIN_ID = 9
ERA_DIAMOND_PROXY_ADDR = "0x0000000000000000000000000000000000000000"
CHAIN_ADMIN_ADDR = "0x0000000000000000000000000000000000000000"
CTM_ASSET_INFO = "0xf9664f4324c1400fa5c3822d667f30e873f53f1b8033180cd15fe41c1e2355c6"

L1_CHAIN_ID = 9
[contracts.test]
dummy_verifier = true
easy_priority_mode = false
