# Addresses of the deployed ZKsync contracts.
# Values of this file are updated automatically by the contract deploy script.

[contracts]
ADMIN_FACET_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
DIAMOND_INIT_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
DIAMOND_UPGRADE_INIT_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
DEFAULT_UPGRADE_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
MAILBOX_FACET_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
EXECUTOR_FACET_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
GOVERNANCE_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
REMOTE_GOVERNANCE_IMPL_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
REMOTE_GOVERNANCE_PROXY_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
GETTERS_FACET_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
VERIFIER_ADDR = "0xDAbb67b676F5b01FcC8997Cc8439846D0d8078ca"
DIAMOND_PROXY_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_MULTICALL3_ADDR = "0xcA11bde05977b3631167028862bE2a173976CA11"
L1_ERC20_BRIDGE_PROXY_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_ERC20_BRIDGE_IMPL_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L2_ERC20_BRIDGE_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L2_TESTNET_PAYMASTER_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_ALLOW_LIST_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
CREATE2_FACTORY_ADDR = "0xce0042B868300000d44A59004Da54A005ffdcf9f"
VALIDATOR_TIMELOCK_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
VALIDATOR_TIMELOCK_EXECUTION_DELAY = 0
RECURSION_SCHEDULER_LEVEL_VK_HASH = "0x18518ce15be02847459f304b1567cb914ae357eca82af07c09582e78592b987b"
RECURSION_NODE_LEVEL_VK_HASH = "0x1186ec268d49f1905f8d9c1e9d39fc33e98c74f91d91a21b8f7ef78bd09a8db8"
RECURSION_LEAF_LEVEL_VK_HASH = "0x101e08b00193e529145ee09823378ef51a3bc8966504064f1f6ba3f1ba863210"
RECURSION_CIRCUITS_SET_VKS_HASH = "0x18c1639094f58177409186e8c48d9f577c9410901d2f1d486b3e7d6cf553ae4c"
GENESIS_TX_HASH = "0xb99ebfea46cbe05a21cd80fe5597d97b204befc52a16303f579c607dc1ac2e2e"
GENESIS_ROOT = "0x76b1518bd643a71fca7fff60f05a9edb25bb9b220128a51fe000cff266887386"
GENESIS_BATCH_COMMITMENT = "0xe9c56565ce6f8413f8f9861d99cc76d551a9270855eb99bae415d6cef4eccf27"
PRIORITY_TX_MAX_GAS_LIMIT = 72000000
DEPLOY_L2_BRIDGE_COUNTERPART_GAS_LIMIT = 10000000
GENESIS_PROTOCOL_VERSION = "25"
GENESIS_PROTOCOL_SEMANTIC_VERSION = "0.25.2"
L1_WETH_BRIDGE_IMPL_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L1_WETH_BRIDGE_PROXY_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L1_WETH_TOKEN_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L2_WETH_BRIDGE_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L2_WETH_TOKEN_IMPL_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L2_WETH_TOKEN_PROXY_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
BLOB_VERSIONED_HASH_RETRIEVER_ADDR = "0x0000000000000000000000000000000000000000"
GENESIS_ROLLUP_LEAF_INDEX = "64" 

# Ecosystem-wide params
L1_ROLLUP_DA_VALIDATOR = "0x0000000000000000000000000000000000000000"
L1_VALIDIUM_DA_VALIDATOR = "0x0000000000000000000000000000000000000000"

# Chain-specific params
L1_DA_VALIDATOR_ADDR = "0x0000000000000000000000000000000000000000"
L2_DA_VALIDATOR_ADDR = "0x0000000000000000000000000000000000000000"
L1_RELAYED_SL_DA_VALIDATOR = "0x0000000000000000000000000000000000000000"

L1_SHARED_BRIDGE_IMPL_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
# These are currently not used, but will be used once the shared bridge is up
BRIDGEHUB_PROXY_ADDR = "0x0000000000000000000000000000000000000000"
BRIDGEHUB_IMPL_ADDR = "0x0000000000000000000000000000000000000000"
STATE_TRANSITION_PROXY_ADDR = "0x0000000000000000000000000000000000000000"
STATE_TRANSITION_IMPL_ADDR = "0x0000000000000000000000000000000000000000"
TRANSPARENT_PROXY_ADMIN_ADDR = "0x0000000000000000000000000000000000000000"
L2_PROXY_ADMIN_ADDR = "0x0000000000000000000000000000000000000000"
BASE_TOKEN_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
BASE_TOKEN_BRIDGE_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
GENESIS_UPGRADE_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
MAX_NUMBER_OF_HYPERCHAINS = 100
L1_SHARED_BRIDGE_PROXY_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L2_SHARED_BRIDGE_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L2_SHARED_BRIDGE_IMPL_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_NATIVE_TOKEN_VAULT_IMPL_ADDR ="0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_NATIVE_TOKEN_VAULT_PROXY_ADDR ="0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L2_NATIVE_TOKEN_VAULT_IMPL_ADDR ="0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L2_NATIVE_TOKEN_VAULT_PROXY_ADDR ="0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
STM_DEPLOYMENT_TRACKER_IMPL_ADDR ="0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
STM_DEPLOYMENT_TRACKER_PROXY_ADDR ="0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
MESSAGE_ROOT_IMPL_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
MESSAGE_ROOT_PROXY_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
FRI_RECURSION_LEAF_LEVEL_VK_HASH = "0xf9664f4324c1400fa5c3822d667f30e873f53f1b8033180cd15fe41c1e2355c6"
FRI_RECURSION_NODE_LEVEL_VK_HASH = "0xf520cd5b37e74e19fdb369c8d676a04dce8a19457497ac6686d2bb95d94109c8"
FRI_RECURSION_SCHEDULER_LEVEL_VK_HASH = "0xe6ba9d6b042440c480fa1c7182be32387db6e90281e82f37398d3f98f63f098a"
SNARK_WRAPPER_VK_HASH = "0x14f97b81e54b35fe673d8708cc1a19e1ea5b5e348e12d31e39824ed4f42bbca2"
SHARED_BRIDGE_UPGRADE_STORAGE_SWITCH = 0
ERA_CHAIN_ID = 9
ERA_DIAMOND_PROXY_ADDR = "0x0000000000000000000000000000000000000000"
CHAIN_ADMIN_ADDR = "0x0000000000000000000000000000000000000000"

L1_CHAIN_ID = 9
[contracts.test]
dummy_verifier = true
easy_priority_mode = false
