# Addresses of the deployed zkSync contracts.
# Values of this file are updated automatically by the contract deploy script.

[contracts]
ADMIN_FACET_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
DIAMOND_INIT_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
DIAMOND_UPGRADE_INIT_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
DEFAULT_UPGRADE_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
MAILBOX_FACET_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
EXECUTOR_FACET_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
GOVERNANCE_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
GETTERS_FACET_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
VERIFIER_ADDR = "0xDAbb67b676F5b01FcC8997Cc8439846D0d8078ca"
DIAMOND_PROXY_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_MULTICALL3_ADDR = "0xcA11bde05977b3631167028862bE2a173976CA11"
L1_ERC20_BRIDGE_PROXY_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_ERC20_BRIDGE_IMPL_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L2_ERC20_BRIDGE_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L2_TESTNET_PAYMASTER_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L1_ALLOW_LIST_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
CREATE2_FACTORY_ADDR = "0xce0042B868300000d44A59004Da54A005ffdcf9f"
VALIDATOR_TIMELOCK_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
VALIDATOR_TIMELOCK_EXECUTION_DELAY = 0
RECURSION_SCHEDULER_LEVEL_VK_HASH = "0x18518ce15be02847459f304b1567cb914ae357eca82af07c09582e78592b987b"
RECURSION_NODE_LEVEL_VK_HASH = "0x1186ec268d49f1905f8d9c1e9d39fc33e98c74f91d91a21b8f7ef78bd09a8db8"
RECURSION_LEAF_LEVEL_VK_HASH = "0x101e08b00193e529145ee09823378ef51a3bc8966504064f1f6ba3f1ba863210"
RECURSION_CIRCUITS_SET_VKS_HASH = "0x18c1639094f58177409186e8c48d9f577c9410901d2f1d486b3e7d6cf553ae4c"
GENESIS_TX_HASH = "0xb99ebfea46cbe05a21cd80fe5597d97b204befc52a16303f579c607dc1ac2e2e"
GENESIS_ROOT = "0x567d8b8a3cdd9ec7f81a610420e6035841b811876f6ebf74298c6511a05b35f9"
GENESIS_BATCH_COMMITMENT = "0x57feca2ef8f8b69f4d1637760e321228893e6e18cd9147fcdbe6c6f51e9a8557"
PRIORITY_TX_MAX_GAS_LIMIT = 72000000
DEPLOY_L2_BRIDGE_COUNTERPART_GAS_LIMIT = 10000000
GENESIS_ROLLUP_LEAF_INDEX = "56"
GENESIS_PROTOCOL_VERSION = "24"
GENESIS_PROTOCOL_SEMANTIC_VERSION = "0.24.0"
L1_WETH_BRIDGE_IMPL_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L1_WETH_BRIDGE_PROXY_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L1_WETH_TOKEN_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L2_WETH_BRIDGE_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L2_WETH_TOKEN_IMPL_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
L2_WETH_TOKEN_PROXY_ADDR = "0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
BLOB_VERSIONED_HASH_RETRIEVER_ADDR = "0x0000000000000000000000000000000000000000"

L1_SHARED_BRIDGE_IMPL_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
# These are currently not used, but will be used once the shared bridge is up
BRIDGEHUB_PROXY_ADDR = "0x0000000000000000000000000000000000000000"
BRIDGEHUB_IMPL_ADDR = "0x0000000000000000000000000000000000000000"
STATE_TRANSITION_PROXY_ADDR = "0x0000000000000000000000000000000000000000"
STATE_TRANSITION_IMPL_ADDR = "0x0000000000000000000000000000000000000000"
TRANSPARENT_PROXY_ADMIN_ADDR = "0x0000000000000000000000000000000000000000"
BASE_TOKEN_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
BASE_TOKEN_BRIDGE_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
GENESIS_UPGRADE_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
MAX_NUMBER_OF_HYPERCHAINS = 100
L1_SHARED_BRIDGE_PROXY_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L2_SHARED_BRIDGE_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
L2_SHARED_BRIDGE_IMPL_ADDR = "0xFC073319977e314F251EAE6ae6bE76B0B3BAeeCF"
FRI_RECURSION_LEAF_LEVEL_VK_HASH = "0xcc4ac1853353538a166f5c2dde2c24e7e6c461dce8e3dc47d81e9139e1719456"
FRI_RECURSION_NODE_LEVEL_VK_HASH = "0xf520cd5b37e74e19fdb369c8d676a04dce8a19457497ac6686d2bb95d94109c8"
FRI_RECURSION_SCHEDULER_LEVEL_VK_HASH = "0x712bb009b5d5dc81c79f827ca0abff87b43506a8efed6028a818911d4b1b521f"
SNARK_WRAPPER_VK_HASH = "0xb45190a52235abe353afd606a9144728f807804f5282df9247e27c56e817ccd6"
SHARED_BRIDGE_UPGRADE_STORAGE_SWITCH = 0
ERA_CHAIN_ID = 9
ERA_DIAMOND_PROXY_ADDR = "0x0000000000000000000000000000000000000000"
[contracts.test]
dummy_verifier = true
easy_priority_mode = false
