# Configuration for the External Price API crate

[external_price_api_client]

# What source to use for the external price API. Currently only options are "forced", "no-op", and "coingecko".
source = "forced"

[external_price_api_client.forced]
numerator = 314
denominator = 1000