[fri_prover]
setup_data_path = "data/keys"
prometheus_port = 3315
max_attempts = 10
generation_timeout_in_secs = 600
setup_load_mode = "FromDisk"
specialized_group_id = 100
queue_capacity = 10
witness_vector_receiver_port = 3316
zone_read_url = "http://metadata.google.internal/computeMetadata/v1/instance/zone"
availability_check_interval_in_secs = 10
