[fri_proof_compressor]
compression_mode = 5
prometheus_listener_port = 3321
prometheus_pushgateway_url = "http://127.0.0.1:9091"
prometheus_push_interval_ms = 100
generation_timeout_in_secs = 3600
max_attempts = 5
universal_setup_path = "../keys/setup/setup_compact.key"
universal_setup_download_url = "https://storage.googleapis.com/matterlabs-setup-keys-us/setup-keys/setup_compact.key"
verify_wrapper_proof = true
