[fri_witness]
generation_timeout_in_secs = 900
basic_generation_timeout_in_secs = 900
leaf_generation_timeout_in_secs = 900
node_generation_timeout_in_secs = 900
recursion_tip_generation_timeout_in_secs = 900
scheduler_generation_timeout_in_secs = 900
max_attempts = 10
prometheus_listener_port = 3116
