[house_keeper]
l1_batch_metrics_reporting_interval_ms = 10000
gpu_prover_queue_reporting_interval_ms = 10000
prover_job_retrying_interval_ms = 300000
prover_stats_reporting_interval_ms = 5000
witness_job_moving_interval_ms = 30000
witness_generator_stats_reporting_interval_ms = 10000
fri_witness_job_moving_interval_ms = 40000
fri_prover_job_retrying_interval_ms = 30000
fri_witness_generator_job_retrying_interval_ms = 30000
prover_db_pool_size = 2
fri_prover_stats_reporting_interval_ms = 30000
fri_proof_compressor_job_retrying_interval_ms = 30000
fri_proof_compressor_stats_reporting_interval_ms = 10000
fri_prover_job_archiver_reporting_interval_ms = 1800000
fri_prover_job_archiver_archiving_interval_ms = 172800