[prover.non_gpu]
prometheus_port=3313
initial_setup_key_path="./../../../keys/setup/setup_2^22.key"
key_download_url="https://storage.googleapis.com/matterlabs-setup-keys-us/setup-keys/setup_2^22.key"
generation_timeout_in_secs=2700
number_of_threads=22
max_attempts=1
polling_duration_in_millis=750
setup_keys_path="/usr/src/setup-keys"
number_of_setup_slots=2
assembly_receiver_port=17791
assembly_receiver_poll_time_in_millis=250
assembly_queue_capacity=1
specialized_prover_group_id=0

[prover.two_gpu_forty_gb_mem]
prometheus_port=3313
initial_setup_key_path="./../../../keys/setup/setup_2^26.key"
key_download_url="https://storage.googleapis.com/matterlabs-setup-keys-us/setup-keys/setup_2^26.key"
generation_timeout_in_secs=2700
number_of_threads=5
max_attempts=1
polling_duration_in_millis=750
setup_keys_path="/usr/src/setup-keys"
number_of_setup_slots=5
assembly_receiver_port=17791
assembly_receiver_poll_time_in_millis=250
assembly_queue_capacity=3
specialized_prover_group_id=1

[prover.one_gpu_eighty_gb_mem]
prometheus_port=3313
initial_setup_key_path="./../../../keys/setup/setup_2^26.key"
key_download_url="https://storage.googleapis.com/matterlabs-setup-keys-us/setup-keys/setup_2^26.key"
generation_timeout_in_secs=2700
number_of_threads=5
max_attempts=1
polling_duration_in_millis=750
setup_keys_path="/usr/src/setup-keys"
number_of_setup_slots=5
assembly_receiver_port=17791
assembly_receiver_poll_time_in_millis=250
assembly_queue_capacity=3
specialized_prover_group_id=2

[prover.two_gpu_eighty_gb_mem]
prometheus_port=3313
initial_setup_key_path="./../../../keys/setup/setup_2^26.key"
key_download_url="https://storage.googleapis.com/matterlabs-setup-keys-us/setup-keys/setup_2^26.key"
generation_timeout_in_secs=2700
number_of_threads=9
max_attempts=1
polling_duration_in_millis=750
setup_keys_path="/usr/src/setup-keys"
number_of_setup_slots=11
assembly_receiver_port=17791
assembly_receiver_poll_time_in_millis=250
assembly_queue_capacity=4
specialized_prover_group_id=3

[prover.four_gpu_eighty_gb_mem]
prometheus_port=3313
initial_setup_key_path="./../../../keys/setup/setup_2^26.key"
key_download_url="https://storage.googleapis.com/matterlabs-setup-keys-us/setup-keys/setup_2^26.key"
generation_timeout_in_secs=2700
number_of_threads=18
max_attempts=1
polling_duration_in_millis=750
setup_keys_path="/usr/src/setup-keys"
number_of_setup_slots=18
assembly_receiver_port=17791
assembly_receiver_poll_time_in_millis=250
assembly_queue_capacity=20
specialized_prover_group_id=4
