# Environment configuration for the Rust code
# We don't provide the group name like `[rust]` here, because we don't want
# these variables to be prefixed during the compiling. 

# `RUST_LOG` environment variable for `env_logger`
# Here we use TOML multiline strings: newlines will be trimmed.
RUST_LOG="""\
zksync_node_framework=info,\
zksync_block_reverter=info,\
zksync_commitment_generator=info,\
zksync_node_db_pruner=info,\
zksync_eth_sender=info,\
zksync_node_fee_model=info,\
zksync_node_genesis=info,\
zksync_house_keeper=info,\
zksync_proof_data_handler=info,\
zksync_shared_metrics=info,\
zksync_node_test_utils=info,\
zksync_vm_runner=info,\
zksync_node_test_utils=info,\
zksync_state_keeper=info,\
zksync_reorg_detector=info,\
zksync_consistency_checker=info,\
zksync_metadata_calculator=info,\
zksync_node_sync=info,\
zksync_node_consensus=info,\
zksync_contract_verification_server=info,\
zksync_node_api_server=info,\
zksync_tee_verifier_input_producer=info,\
zksync_consensus_bft=info,\
zksync_consensus_network=info,\
zksync_consensus_storage=info,\
zksync_core_leftovers=debug,\
zksync_server=debug,\
zksync_contract_verifier=debug,\
zksync_dal=info,\
zksync_db_connection=info,\
zksync_eth_client=info,\
zksync_eth_watch=debug,\
zksync_storage=info,\
zksync_db_manager=info,\
zksync_merkle_tree=info,\
zksync_state=debug,\
zksync_utils=debug,\
zksync_queued_job_processor=info,\
zksync_types=info,\
zksync_mempool=debug,\
loadnext=info,\
vm=info,\
zksync_object_store=info,\
zksync_external_node=info,\
zksync_witness_generator=info,\
zksync_prover_fri=info,\
zksync_witness_vector_generator=info,\
zksync_web3_decl=debug,\
zksync_health_check=debug,\
zksync_proof_fri_compressor=info,\
vise_exporter=debug,\
snapshots_creator=debug,\
zksync_base_token_adjuster=debug,\
zksync_external_price_api=debug,\
"""

# `RUST_BACKTRACE` variable
RUST_BACKTRACE="full"
RUST_LIB_BACKTRACE="1"
