[package]
name = "admin-tools"
version = "0.1.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
description = "Admin tools CLI for zkSync"
publish = false # We don't want to publish our binaries.

[dependencies]
anyhow = "1.0"
chrono = "^0.4"
clap = { version = "4.0", features = ["derive"] }
dotenvy = "^0.15"
tokio = { version = "1", features = ["full"] }

zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_dal = { path = "../../lib/dal", version = "1.0" }


