[package]
name = "block_reverter"
description = "Utility to revert blocks"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
zksync_config = { workspace = true, features = ["observability_ext"] }
zksync_dal.workspace = true
zksync_object_store.workspace = true
zksync_types.workspace = true
zksync_block_reverter.workspace = true
zksync_vlog.workspace = true
zksync_contracts.workspace = true

anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
serde_json.workspace = true
