[package]
name = "zksync_core"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync-era"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
zksync_state = { path = "../../lib/state", version = "1.0" }
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_dal = { path = "../../lib/dal", version = "1.0" }
zksync_config = { path = "../../lib/config", version = "1.0" }
zksync_utils = { path = "../../lib/utils", version = "1.0" }
zksync_contracts = { path = "../../lib/contracts", version = "1.0" }
zksync_eth_client = { path = "../../lib/eth_client", version = "1.0" }
zksync_eth_signer = { path = "../../lib/eth_signer", version = "1.0" }
zksync_mempool = { path = "../../lib/mempool", version = "1.0" }
zksync_prover_utils = { path = "../../lib/prover_utils", version = "1.0" }
zksync_queued_job_processor = { path = "../../lib/queued_job_processor", version = "1.0" }
zksync_circuit_breaker = { path = "../../lib/circuit_breaker", version = "1.0" }
vm = { path = "../../lib/vm", version = "0.1.0" }
zksync_storage = { path = "../../lib/storage", version = "1.0" }
zksync_merkle_tree = { path = "../../lib/merkle_tree", version = "1.0" }
zksync_mini_merkle_tree = { path = "../../lib/mini_merkle_tree", version = "1.0" }
zksync_verification_key_generator_and_server = { path = "../verification_key_generator_and_server", version = "1.0" }
prometheus_exporter = { path = "../../lib/prometheus_exporter", version = "1.0" }
zksync_web3_decl = { path = "../../lib/web3_decl", version = "1.0", default-features = false, features = [
    "server", "client"
] }
zksync_object_store = { path = "../../lib/object_store", version = "1.0" }
zksync_health_check = { path = "../../lib/health_check", version = "0.1.0" }
vlog = { path = "../../lib/vlog", version = "1.0" }

multivm = { path = "../../lib/multivm", version = "0.1.0" }

clap = { version = "4.2.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
metrics = "0.20"
itertools = "0.10.3"
ctrlc = { version = "3.1", features = ["termination"] }
rand = "0.8"

tokio = { version = "1", features = ["time"] }
futures = { version = "0.3", features = ["compat"] }
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
bitflags = "1.3.2"

# API dependencies
jsonrpc-core = { git = "https://github.com/matter-labs/jsonrpc.git", branch = "master" }
jsonrpc-core-client = { git = "https://github.com/matter-labs/jsonrpc.git", branch = "master" } # Required for the RPC trait
jsonrpc-http-server = { git = "https://github.com/matter-labs/jsonrpc.git", branch = "master" }
jsonrpc-ws-server = { git = "https://github.com/matter-labs/jsonrpc.git", branch = "master" }
jsonrpc-derive = { git = "https://github.com/matter-labs/jsonrpc.git", branch = "master" }
jsonrpc-pubsub = { git = "https://github.com/matter-labs/jsonrpc.git", branch = "master" }
num = { version = "0.3.1", features = ["serde"] }
bigdecimal = { version = "0.2.2", features = ["serde"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
hex = "0.4"
governor = "0.4.2"
tower-http = { version = "0.4.1", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
axum = { version = "0.6.19", default-features = false, features = ["http1", "json", "tokio"] }

actix-rt = "2.2.0"
actix-cors = "0.6.0-beta.2"
actix-web = "4.0.0-beta.8"

tracing = "0.1.26"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[dev-dependencies]
db_test_macro = { path = "../../lib/db_test_macro", version = "0.1.0" }

assert_matches = "1.5"
once_cell = "1.7"
tempfile = "3.0.2"
