[package]
name = "zksync_witness_generator"
version = "0.1.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync-era"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
vise = { git = "https://github.com/matter-labs/vise.git", version = "0.1.0", rev = "1c9cc500e92cf9ea052b230e114a6f9cce4fb2c1" }

zksync_dal = { path = "../../core/lib/dal" }
zksync_config = { path = "../../core/lib/config" }
zksync_prover_interface = { path = "../../core/lib/prover_interface" }
zksync_env_config = { path = "../../core/lib/env_config" }
zksync_system_constants = { path = "../../core/lib/constants" }
prometheus_exporter = { path = "../../core/lib/prometheus_exporter" }
vlog = { path = "../../core/lib/vlog" }
zksync_queued_job_processor = { path = "../../core/lib/queued_job_processor" }
multivm = { path = "../../core/lib/multivm", version = "0.1.0" }
zksync_object_store = { path = "../../core/lib/object_store" }
zksync_types = { path = "../../core/lib/types" }
zksync_state = { path = "../../core/lib/state" }
zksync_utils = { path = "../../core/lib/utils" }
vk_setup_data_generator_server_fri = { path = "../vk_setup_data_generator_server_fri" }
zksync_prover_fri_types = { path = "../prover_fri_types" }
zksync_prover_fri_utils = { path = "../prover_fri_utils" }

zkevm_test_harness = { git = "https://github.com/matter-labs/era-zkevm_test_harness.git", branch = "v1.4.1" }
circuit_definitions = { git = "https://github.com/matter-labs/era-zkevm_test_harness.git", branch = "v1.4.1", features = [
    "log_tracing",
] }
zk_evm = { git = "https://github.com/matter-labs/era-zk_evm.git", branch = "v1.4.1" }

anyhow = "1.0"
tracing = "0.1"
tokio = { version = "1", features = ["time"] }
futures = { version = "0.3", features = ["compat"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
bincode = "1"
rand = "0.8"
hex = "0.4"
structopt = "0.3.26"
ctrlc = { version = "3.1", features = ["termination"] }
const-decoder = "0.3.0"
