[package]
name = "zksync_witness_generator"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
vise.workspace = true
prover_dal.workspace = true
zksync_dal.workspace = true
zksync_config.workspace = true
zksync_prover_interface.workspace = true
zksync_env_config.workspace = true
zksync_system_constants.workspace = true
prometheus_exporter.workspace = true
vlog.workspace = true
zksync_queued_job_processor.workspace = true
multivm.workspace = true
zksync_object_store.workspace = true
zksync_types.workspace = true
zksync_state.workspace = true
zksync_utils.workspace = true
vk_setup_data_generator_server_fri.workspace = true
zksync_prover_fri_types.workspace = true
zksync_prover_fri_utils.workspace = true

zkevm_test_harness = { workspace = true }
circuit_definitions = { workspace = true, features = [ "log_tracing" ] }
zk_evm.workspace = true

anyhow.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["time", "macros"] }
futures = { workspace = true, features = ["compat"] }
serde = { workspace = true, features = ["derive"] }
async-trait.workspace = true
bincode.workspace = true
rand.workspace = true
structopt.workspace = true
ctrlc = { workspace = true, features = ["termination"] }
once_cell.workspace = true
tempfile.workspace = true

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.5"

[dev-dependencies]
const-decoder = "0.3.0"
