[package]
name = "snapshots_creator"
description = "Tool to create ZKsync state snapshots"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
vise.workspace = true
zksync_config = { workspace = true, features = ["observability_ext"] }
zksync_dal.workspace = true
zksync_types.workspace = true
zksync_object_store.workspace = true
zksync_vlog.workspace = true

anyhow.workspace = true
structopt.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
futures.workspace = true

[dev-dependencies]
rand.workspace = true
test-casing.workspace = true
