[package]
name = "zksync_node_fee_model"
description = "ZKsync fee model"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
vise.workspace = true
zksync_types.workspace = true
zksync_dal = { workspace = true, features = ["node_framework"] }
zksync_config.workspace = true
zksync_eth_client = { workspace = true, features = ["node_framework"] }
zksync_web3_decl.workspace = true
zksync_node_framework.workspace = true
zksync_shared_di.workspace = true

tokio = { workspace = true, features = ["time"] }
anyhow.workspace = true
async-trait.workspace = true
tracing.workspace = true

[dev-dependencies]
test-casing.workspace = true
zksync_node_test_utils.workspace = true
zksync_node_genesis.workspace = true
