[package]
name = "zksync_witness_vector_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zksync_types = { path = "../../core/lib/types" }
zksync_config = { path = "../../core/lib/config" }
zksync_env_config = { path = "../../core/lib/env_config" }
zksync_object_store = { path = "../../core/lib/object_store" }
zksync_prover_fri_utils = { path = "../prover_fri_utils" }
zksync_utils = { path = "../../core/lib/utils" }
prometheus_exporter = { path = "../../core/lib/prometheus_exporter" }
zksync_prover_fri_types = { path = "../prover_fri_types" }
zksync_prover_utils = { path = "../../core/lib/prover_utils" }
zksync_queued_job_processor = { path = "../../core/lib/queued_job_processor" }
vk_setup_data_generator_server_fri = { path = "../vk_setup_data_generator_server_fri" }
vlog = { path = "../../core/lib/vlog" }
zksync_db_connection = { path = "../../core/lib/db_connection"}
zksync_prover_dal = { path = "../prover_dal"}

anyhow = "1.0"
tracing = "0.1"
structopt = "0.3.26"
tokio = { version = "1", features = ["time"] }
futures = { version = "0.3", features = ["compat"] }
ctrlc = { version = "3.1", features = ["termination"] }
metrics = "0.21"
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"
queues = "1.1.0"
bincode = "1.0"
