[package]
name = "zksync_prover_job_monitor"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zksync_vlog.workspace = true
zksync_prover_dal.workspace = true
zksync_task_management.workspace = true
zksync_types.workspace = true
zksync_prover_config.workspace = true
zksync_db_connection.workspace = true
zksync_prover_task.workspace = true

vise.workspace = true

tokio = { workspace = true, features = ["time", "macros"] }
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
ctrlc = { workspace = true, features = ["termination"] }
tracing.workspace = true
async-trait.workspace = true
serde.workspace = true
axum.workspace = true
