[package]
name = "zksync_vm_runner"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zksync_multivm.workspace = true
zksync_types.workspace = true
zksync_dal.workspace = true
zksync_contracts.workspace = true
zksync_state.workspace = true
zksync_storage.workspace = true
zksync_state_keeper.workspace = true
zksync_utils.workspace = true
zksync_vm_utils.workspace = true

tokio = { workspace = true, features = ["time"] }
anyhow.workspace = true
async-trait.workspace = true
once_cell.workspace = true
tracing.workspace = true
dashmap.workspace = true
vise.workspace = true

[dev-dependencies]
zksync_node_test_utils.workspace = true
zksync_node_genesis.workspace = true
zksync_test_account.workspace = true
backon.workspace = true
futures = { workspace = true, features = ["compat"] }
rand.workspace = true
tempfile.workspace = true
