[package]
name = "zksync_logs_bloom_backfill"
description = "ZKsync logs bloom backfill"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zksync_dal = { workspace = true, features = ["node_framework"] }
zksync_node_framework.workspace = true
zksync_types.workspace = true

anyhow.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["time"] }
tracing.workspace = true

[dev-dependencies]
zksync_vm_interface.workspace = true
