name: Local Node - Build docker image
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag of a built image to deploy (latest2.0 by default)"
        type: string
        required: false
        default: "latest2.0"

jobs:
  build-images:
    name: Local Node - Build and Push Docker Image
    runs-on: [matterlabs-ci-runner]
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          submodules: "recursive"

      - name: setup-env
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo CI=1 >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH
          echo CI=1 >> .env
          echo IN_DOCKER=1 >> .env

      - name: start-services
        run: |
          mkdir -p ./volumes/postgres ./volumes/geth/keystore ./volumes/prysm/beacon ./volumes/prysm/validator
          cp ./docker/prysm/config.yml ./volumes/prysm/
          cp ./docker/geth/password.sec ./docker/geth/jwtsecret ./volumes/geth/
          cp -r ./docker/geth/keystore/ ./volumes/geth/keystore/
          docker-compose -f docker-compose-local-genesis.yml up
          docker-compose -f docker-compose-local-genesis.yml rm -f
          docker-compose --profile runner up -d --wait
          docker ps

      - name: init
        run: |
          ci_run git config --global --add safe.directory /usr/src/zksync
          ci_run git config --global --add safe.directory /usr/src/zksync/sdk/binaryen
          ci_run git config --global --add safe.directory /usr/src/zksync/etc/system-contracts
          ci_run git config --global --add safe.directory /usr/src/zksync/contracts

          ci_run zk
          ci_run zk run yarn
          ci_run cp etc/tokens/{test,localhost}.json
          ci_run zk compiler all
          ci_run zk contract build
          ci_run zk f yarn run l2-contracts build

      - name: update-image
        run: |
          ci_run docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          ci_run zk docker build server-v2
          ci_run gcloud auth configure-docker us-docker.pkg.dev -q
          ci_run zk docker push local-node --custom-tag ${{ inputs.image_tag }}
